#!/usr/bin/env python3

from youtube.downloader import yt_download
from video.tools import get_frames
from utils.logger import *
import sys

if len(sys.argv) != 4:
    print()
    print("Usage: ")
    print("     {} <youtube_url> <frame_names> <sample_rate_ms> [YouTube video quality]".format(sys.argv[0]))
    print()
    print("     YouTube Video Quality: 144p, 240p, 360p, (480p) default, 720p, 1080p")
    print()
    exit(1)

# desired_video = "https://www.youtube.com/watch?v=OaSwzjjVid4" # 3d printer video
# desired_video = "https://www.youtube.com/watch?v=bH6OGXNUCC0" # sample SHORT video
desired_video = sys.argv[1]
frame_name = sys.argv[2]
sample_rate_ms = sys.argv[3]
if sys.argv == 5:
    video_quality = sys.argv[4]
else:
    video_quality = "480p"

video_output_directory = "/app/media/youtube/"
images_output_directory = "/app/media/images/"

filename = yt_download(desired_video, video_output_directory, video_quality)
log_info("File was saved in {}".format(filename))

get_frames(images_output_directory, filename, frame_name, sample_rate_ms)
