#!/usr/bin/env python3

from youtube.downloader import yt_download
from video.tools import get_frames
from utils.logger import *
import sys

if len(sys.argv) < 2:
    print()
    print("Usage: ")
    print("     {} <youtube_url> [YouTube video quality]".format(sys.argv[0]))
    print()
    print("     YouTube Video Quality: 144p, 240p, (360p) default, 480p, 720p, 1080p")
    print()
    exit(1)

desired_video = sys.argv[1]
if sys.argv == 5:
    video_quality = sys.argv[2]
else:
    video_quality = "360p"

video_output_directory = "/app/media/youtube/"

filename = yt_download(desired_video, video_output_directory, video_quality)
print("Video was saved in {}".format(filename))
